name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
      - name: make build
        run: make all
