name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: make all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make build
        uses: docker://golang:latest
        with:
          args: make all
